rrbot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # JointTrajectoryController ----------------------------------
  joints_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - joint1
      - joint2
    gains:
      joint1: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 1}
      joint2: {p: 100.0, i: 0.01, d: 10.0, i_clamp: 1}
